--------------------------------------------------------
--  File created - Wednesday-September-11-2024   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table SUPPLIER
--------------------------------------------------------

  CREATE TABLE "CPAYTCOR"."SUPPLIER" 
   (	"SUPPLIER_ID" NUMBER GENERATED BY DEFAULT AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"SUPPLIER_NAME" VARCHAR2(255 BYTE), 
	"CONTACT_NAME" VARCHAR2(255 BYTE), 
	"ADDRESS" VARCHAR2(500 BYTE), 
	"CONTACT_NUMBER" VARCHAR2(25 BYTE), 
	"EMAIL" VARCHAR2(255 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into CPAYTCOR.SUPPLIER
SET DEFINE OFF;
Insert into CPAYTCOR.SUPPLIER (SUPPLIER_ID,SUPPLIER_NAME,CONTACT_NAME,ADDRESS,CONTACT_NUMBER,EMAIL) values (1,'Digisay Co. Ltd.','Berry Parker','68, Marock Lane, - , Vacoas, Mauritius','57841266, 6028010','bparker@intnet.mu');
Insert into CPAYTCOR.SUPPLIER (SUPPLIER_ID,SUPPLIER_NAME,CONTACT_NAME,ADDRESS,CONTACT_NUMBER,EMAIL) values (2,'Emtello Ltd','Megan Hembly','998, Bistrop Street, Marlone, Pamplemousses, Mauritius','2420641, 57841698','mhem@my-t.mu');
Insert into CPAYTCOR.SUPPLIER (SUPPLIER_ID,SUPPLIER_NAME,CONTACT_NAME,ADDRESS,CONTACT_NUMBER,EMAIL) values (3,'Fireland Bros.','Amelia Bridney','-, Main court bldg, Nerling road, Moka, Mauritius','59480015','abridney@gmail.com');
Insert into CPAYTCOR.SUPPLIER (SUPPLIER_ID,SUPPLIER_NAME,CONTACT_NAME,ADDRESS,CONTACT_NUMBER,EMAIL) values (4,'Foxy Electronics','Reddy Floyd','C47, Green Street, -, Savanne, Mauritius','52845412','foxyelec@yahoo.fr');
Insert into CPAYTCOR.SUPPLIER (SUPPLIER_ID,SUPPLIER_NAME,CONTACT_NAME,ADDRESS,CONTACT_NUMBER,EMAIL) values (5,'Jinfix Computers','Jordan Liu Min','93, Bardeau lane, - , Port Louis, Mauritius','58412556,2195412','contactus@jinfixcomputers.com');
Insert into CPAYTCOR.SUPPLIER (SUPPLIER_ID,SUPPLIER_NAME,CONTACT_NAME,ADDRESS,CONTACT_NUMBER,EMAIL) values (6,'Lamboni Stat Inc.','Frederic Pey','9, Lamu Building, Stacy Street, Camp Hill, Pamplemousses','52557435','manustat@gmail.com');
Insert into CPAYTCOR.SUPPLIER (SUPPLIER_ID,SUPPLIER_NAME,CONTACT_NAME,ADDRESS,CONTACT_NUMBER,EMAIL) values (7,'Mottoway Corp.','Stevens Seernah','B312, Cite la Cure, Jean XXIII Road, Port Louis, Mauritius','57942513','steseer@mottoway.com');
Insert into CPAYTCOR.SUPPLIER (SUPPLIER_ID,SUPPLIER_NAME,CONTACT_NAME,ADDRESS,CONTACT_NUMBER,EMAIL) values (8,'Pegasus Ltd','Georges Neeroo','40, Ferney Way, Mission Road, Curepipe, Mauritius','4615841, 57412545','geonee@pegasus.mu');
Insert into CPAYTCOR.SUPPLIER (SUPPLIER_ID,SUPPLIER_NAME,CONTACT_NAME,ADDRESS,CONTACT_NUMBER,EMAIL) values (9,'Safedest Taxi Services','Steeve Narsimullu','-, Le clezio street, Barbley wood, Highlands, Mauritius','58741002, 2174512','steeve.nar@safedest.mu');
Insert into CPAYTCOR.SUPPLIER (SUPPLIER_ID,SUPPLIER_NAME,CONTACT_NAME,ADDRESS,CONTACT_NUMBER,EMAIL) values (10,'Stuffie Stationery','Zenhir Belall','67, Bistro Route, Heneral Street, Vacaoas, Mauritius','6547416','info@sstat.com');
--------------------------------------------------------
--  DDL for Index SYS_C0016195
--------------------------------------------------------

  CREATE UNIQUE INDEX "CPAYTCOR"."SYS_C0016195" ON "CPAYTCOR"."SUPPLIER" ("SUPPLIER_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table SUPPLIER
--------------------------------------------------------

  ALTER TABLE "CPAYTCOR"."SUPPLIER" MODIFY ("SUPPLIER_ID" NOT NULL ENABLE);
  ALTER TABLE "CPAYTCOR"."SUPPLIER" MODIFY ("SUPPLIER_NAME" NOT NULL ENABLE);
  ALTER TABLE "CPAYTCOR"."SUPPLIER" ADD PRIMARY KEY ("SUPPLIER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
